// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: cosigner_grpc_server.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CosignerGRPC_SignBlock_FullMethodName                      = "/proto.CosignerGRPC/SignBlock"
	CosignerGRPC_SignBlockECDSA_FullMethodName                 = "/proto.CosignerGRPC/SignBlockECDSA"
	CosignerGRPC_SetEphemeralSecretPartsAndSign_FullMethodName = "/proto.CosignerGRPC/SetEphemeralSecretPartsAndSign"
	CosignerGRPC_GetEphemeralSecretParts_FullMethodName        = "/proto.CosignerGRPC/GetEphemeralSecretParts"
	CosignerGRPC_TransferLeadership_FullMethodName             = "/proto.CosignerGRPC/TransferLeadership"
	CosignerGRPC_GetLeader_FullMethodName                      = "/proto.CosignerGRPC/GetLeader"
	CosignerGRPC_SignECDSA_FullMethodName                      = "/proto.CosignerGRPC/SignECDSA"
	CosignerGRPC_IncSig_FullMethodName                         = "/proto.CosignerGRPC/IncSig"
)

// CosignerGRPCClient is the client API for CosignerGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CosignerGRPCClient interface {
	SignBlock(ctx context.Context, in *CosignerGRPCSignBlockRequest, opts ...grpc.CallOption) (*CosignerGRPCSignBlockResponse, error)
	SignBlockECDSA(ctx context.Context, in *CosignerGRPCSignBlockRequest, opts ...grpc.CallOption) (*CosignerGRPCSignBlockResponse, error)
	SetEphemeralSecretPartsAndSign(ctx context.Context, in *CosignerGRPCSetEphemeralSecretPartsAndSignRequest, opts ...grpc.CallOption) (*CosignerGRPCSetEphemeralSecretPartsAndSignResponse, error)
	GetEphemeralSecretParts(ctx context.Context, in *CosignerGRPCGetEphemeralSecretPartsRequest, opts ...grpc.CallOption) (*CosignerGRPCGetEphemeralSecretPartsResponse, error)
	TransferLeadership(ctx context.Context, in *CosignerGRPCTransferLeadershipRequest, opts ...grpc.CallOption) (*CosignerGRPCTransferLeadershipResponse, error)
	GetLeader(ctx context.Context, in *CosignerGRPCGetLeaderRequest, opts ...grpc.CallOption) (*CosignerGRPCGetLeaderResponse, error)
	SignECDSA(ctx context.Context, in *SignECDSARequest, opts ...grpc.CallOption) (*SignECDSAResponse, error)
	IncSig(ctx context.Context, in *IncSigRequest, opts ...grpc.CallOption) (*IncSigResponse, error)
}

type cosignerGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewCosignerGRPCClient(cc grpc.ClientConnInterface) CosignerGRPCClient {
	return &cosignerGRPCClient{cc}
}

func (c *cosignerGRPCClient) SignBlock(ctx context.Context, in *CosignerGRPCSignBlockRequest, opts ...grpc.CallOption) (*CosignerGRPCSignBlockResponse, error) {
	out := new(CosignerGRPCSignBlockResponse)
	err := c.cc.Invoke(ctx, CosignerGRPC_SignBlock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cosignerGRPCClient) SignBlockECDSA(ctx context.Context, in *CosignerGRPCSignBlockRequest, opts ...grpc.CallOption) (*CosignerGRPCSignBlockResponse, error) {
	out := new(CosignerGRPCSignBlockResponse)
	err := c.cc.Invoke(ctx, CosignerGRPC_SignBlockECDSA_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cosignerGRPCClient) SetEphemeralSecretPartsAndSign(ctx context.Context, in *CosignerGRPCSetEphemeralSecretPartsAndSignRequest, opts ...grpc.CallOption) (*CosignerGRPCSetEphemeralSecretPartsAndSignResponse, error) {
	out := new(CosignerGRPCSetEphemeralSecretPartsAndSignResponse)
	err := c.cc.Invoke(ctx, CosignerGRPC_SetEphemeralSecretPartsAndSign_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cosignerGRPCClient) GetEphemeralSecretParts(ctx context.Context, in *CosignerGRPCGetEphemeralSecretPartsRequest, opts ...grpc.CallOption) (*CosignerGRPCGetEphemeralSecretPartsResponse, error) {
	out := new(CosignerGRPCGetEphemeralSecretPartsResponse)
	err := c.cc.Invoke(ctx, CosignerGRPC_GetEphemeralSecretParts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cosignerGRPCClient) TransferLeadership(ctx context.Context, in *CosignerGRPCTransferLeadershipRequest, opts ...grpc.CallOption) (*CosignerGRPCTransferLeadershipResponse, error) {
	out := new(CosignerGRPCTransferLeadershipResponse)
	err := c.cc.Invoke(ctx, CosignerGRPC_TransferLeadership_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cosignerGRPCClient) GetLeader(ctx context.Context, in *CosignerGRPCGetLeaderRequest, opts ...grpc.CallOption) (*CosignerGRPCGetLeaderResponse, error) {
	out := new(CosignerGRPCGetLeaderResponse)
	err := c.cc.Invoke(ctx, CosignerGRPC_GetLeader_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cosignerGRPCClient) SignECDSA(ctx context.Context, in *SignECDSARequest, opts ...grpc.CallOption) (*SignECDSAResponse, error) {
	out := new(SignECDSAResponse)
	err := c.cc.Invoke(ctx, CosignerGRPC_SignECDSA_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cosignerGRPCClient) IncSig(ctx context.Context, in *IncSigRequest, opts ...grpc.CallOption) (*IncSigResponse, error) {
	out := new(IncSigResponse)
	err := c.cc.Invoke(ctx, CosignerGRPC_IncSig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CosignerGRPCServer is the server API for CosignerGRPC service.
// All implementations must embed UnimplementedCosignerGRPCServer
// for forward compatibility
type CosignerGRPCServer interface {
	SignBlock(context.Context, *CosignerGRPCSignBlockRequest) (*CosignerGRPCSignBlockResponse, error)
	SignBlockECDSA(context.Context, *CosignerGRPCSignBlockRequest) (*CosignerGRPCSignBlockResponse, error)
	SetEphemeralSecretPartsAndSign(context.Context, *CosignerGRPCSetEphemeralSecretPartsAndSignRequest) (*CosignerGRPCSetEphemeralSecretPartsAndSignResponse, error)
	GetEphemeralSecretParts(context.Context, *CosignerGRPCGetEphemeralSecretPartsRequest) (*CosignerGRPCGetEphemeralSecretPartsResponse, error)
	TransferLeadership(context.Context, *CosignerGRPCTransferLeadershipRequest) (*CosignerGRPCTransferLeadershipResponse, error)
	GetLeader(context.Context, *CosignerGRPCGetLeaderRequest) (*CosignerGRPCGetLeaderResponse, error)
	SignECDSA(context.Context, *SignECDSARequest) (*SignECDSAResponse, error)
	IncSig(context.Context, *IncSigRequest) (*IncSigResponse, error)
	mustEmbedUnimplementedCosignerGRPCServer()
}

// UnimplementedCosignerGRPCServer must be embedded to have forward compatible implementations.
type UnimplementedCosignerGRPCServer struct {
}

func (UnimplementedCosignerGRPCServer) SignBlock(context.Context, *CosignerGRPCSignBlockRequest) (*CosignerGRPCSignBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignBlock not implemented")
}
func (UnimplementedCosignerGRPCServer) SignBlockECDSA(context.Context, *CosignerGRPCSignBlockRequest) (*CosignerGRPCSignBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignBlockECDSA not implemented")
}
func (UnimplementedCosignerGRPCServer) SetEphemeralSecretPartsAndSign(context.Context, *CosignerGRPCSetEphemeralSecretPartsAndSignRequest) (*CosignerGRPCSetEphemeralSecretPartsAndSignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEphemeralSecretPartsAndSign not implemented")
}
func (UnimplementedCosignerGRPCServer) GetEphemeralSecretParts(context.Context, *CosignerGRPCGetEphemeralSecretPartsRequest) (*CosignerGRPCGetEphemeralSecretPartsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEphemeralSecretParts not implemented")
}
func (UnimplementedCosignerGRPCServer) TransferLeadership(context.Context, *CosignerGRPCTransferLeadershipRequest) (*CosignerGRPCTransferLeadershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferLeadership not implemented")
}
func (UnimplementedCosignerGRPCServer) GetLeader(context.Context, *CosignerGRPCGetLeaderRequest) (*CosignerGRPCGetLeaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeader not implemented")
}
func (UnimplementedCosignerGRPCServer) SignECDSA(context.Context, *SignECDSARequest) (*SignECDSAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignECDSA not implemented")
}
func (UnimplementedCosignerGRPCServer) IncSig(context.Context, *IncSigRequest) (*IncSigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncSig not implemented")
}
func (UnimplementedCosignerGRPCServer) mustEmbedUnimplementedCosignerGRPCServer() {}

// UnsafeCosignerGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CosignerGRPCServer will
// result in compilation errors.
type UnsafeCosignerGRPCServer interface {
	mustEmbedUnimplementedCosignerGRPCServer()
}

func RegisterCosignerGRPCServer(s grpc.ServiceRegistrar, srv CosignerGRPCServer) {
	s.RegisterService(&CosignerGRPC_ServiceDesc, srv)
}

func _CosignerGRPC_SignBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosignerGRPCSignBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CosignerGRPCServer).SignBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CosignerGRPC_SignBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CosignerGRPCServer).SignBlock(ctx, req.(*CosignerGRPCSignBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CosignerGRPC_SignBlockECDSA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosignerGRPCSignBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CosignerGRPCServer).SignBlockECDSA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CosignerGRPC_SignBlockECDSA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CosignerGRPCServer).SignBlockECDSA(ctx, req.(*CosignerGRPCSignBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CosignerGRPC_SetEphemeralSecretPartsAndSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosignerGRPCSetEphemeralSecretPartsAndSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CosignerGRPCServer).SetEphemeralSecretPartsAndSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CosignerGRPC_SetEphemeralSecretPartsAndSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CosignerGRPCServer).SetEphemeralSecretPartsAndSign(ctx, req.(*CosignerGRPCSetEphemeralSecretPartsAndSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CosignerGRPC_GetEphemeralSecretParts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosignerGRPCGetEphemeralSecretPartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CosignerGRPCServer).GetEphemeralSecretParts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CosignerGRPC_GetEphemeralSecretParts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CosignerGRPCServer).GetEphemeralSecretParts(ctx, req.(*CosignerGRPCGetEphemeralSecretPartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CosignerGRPC_TransferLeadership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosignerGRPCTransferLeadershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CosignerGRPCServer).TransferLeadership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CosignerGRPC_TransferLeadership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CosignerGRPCServer).TransferLeadership(ctx, req.(*CosignerGRPCTransferLeadershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CosignerGRPC_GetLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosignerGRPCGetLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CosignerGRPCServer).GetLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CosignerGRPC_GetLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CosignerGRPCServer).GetLeader(ctx, req.(*CosignerGRPCGetLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CosignerGRPC_SignECDSA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignECDSARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CosignerGRPCServer).SignECDSA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CosignerGRPC_SignECDSA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CosignerGRPCServer).SignECDSA(ctx, req.(*SignECDSARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CosignerGRPC_IncSig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncSigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CosignerGRPCServer).IncSig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CosignerGRPC_IncSig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CosignerGRPCServer).IncSig(ctx, req.(*IncSigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CosignerGRPC_ServiceDesc is the grpc.ServiceDesc for CosignerGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CosignerGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CosignerGRPC",
	HandlerType: (*CosignerGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignBlock",
			Handler:    _CosignerGRPC_SignBlock_Handler,
		},
		{
			MethodName: "SignBlockECDSA",
			Handler:    _CosignerGRPC_SignBlockECDSA_Handler,
		},
		{
			MethodName: "SetEphemeralSecretPartsAndSign",
			Handler:    _CosignerGRPC_SetEphemeralSecretPartsAndSign_Handler,
		},
		{
			MethodName: "GetEphemeralSecretParts",
			Handler:    _CosignerGRPC_GetEphemeralSecretParts_Handler,
		},
		{
			MethodName: "TransferLeadership",
			Handler:    _CosignerGRPC_TransferLeadership_Handler,
		},
		{
			MethodName: "GetLeader",
			Handler:    _CosignerGRPC_GetLeader_Handler,
		},
		{
			MethodName: "SignECDSA",
			Handler:    _CosignerGRPC_SignECDSA_Handler,
		},
		{
			MethodName: "IncSig",
			Handler:    _CosignerGRPC_IncSig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosigner_grpc_server.proto",
}
